version: 2
jobs:
  pip:
    working_directoyr: ~/python-ci
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: sudo pip install -r requirements.txt
  pytest:
    working_directoyr: ~/python-ci
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: sudo pip install -r requirements.txt
      - run:
          command: pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - pip
      - pytest